local YamlHeader = require("MetaFly.model.YamlHeader")

describe("MetaFly.model.YamlHeader", function()
	local tmpdir

	it("creates a new YamlHeader object", function()
		local yh = YamlHeader:new("testfile.md", 1)
		assert.is_table(yh)
		assert.equals("testfile.md", yh.fileName)
		assert.equals(1, yh.bufferNumber)
		assert.is_table(yh.header)
		assert.is_table(yh.headerLines)
		assert.is_table(yh.warnings)
		assert.is_table(yh.mappings)
		assert.is_table(yh.noteData)
		assert.is_table(yh.metaData)
	end)

	describe("parseDocument", function()
		it("returns title as a Lua string for a plain YAML title field", function()
			local yh = YamlHeader:new("testfile.md", -1)
			yh:setHeaderLines({ "---", "title: My Note", "---" })
			local noteData = yh:parseDocument()
			assert.is_not_nil(noteData)
			assert.equals("string", type(noteData.title))
			assert.equals("My Note", noteData.title)
		end)

		it("returns title as a Lua string when value contains special characters", function()
			local yh = YamlHeader:new("testfile.md", -1)
			yh:setHeaderLines({ "---", "Titel: 26.3-2(16.07-29.07)", "---" })
			local noteData = yh:parseDocument()
			assert.is_not_nil(noteData)
			assert.equals("string", type(noteData.title), "title must be a Lua string, not " .. type(noteData.title))
			assert.equals("26.3-2(16.07-29.07)", noteData.title)
		end)

		it("returns title as a Lua string when title comes from aliases list", function()
			local yh = YamlHeader:new("testfile.md", -1)
			yh:setHeaderLines({ "---", "aliases:", "  - 26.3-2(16.07-29.07)", "---" })
			local noteData = yh:parseDocument()
			assert.is_not_nil(noteData)
			assert.equals("string", type(noteData.title), "title from aliases must be a Lua string")
			assert.equals("26.3-2(16.07-29.07)", noteData.title)
		end)
	end)
end)
